### ISSUE TITLE
Software installation instructions missing

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/robo-butler#10]
When [software.yml](https://github.com/raspberrypilearning/robo-butler/blob/master/software.yml) is present, full instructions are required in the [software.md](https://github.com/raspberrypilearning/robo-butler/blob/master/software.md) file.

If these instructions are present in the worksheet or separate files they need to be moved to `software.md`.

See examples in other repos, e.g. [Tweeting Babbage](https://github.com/raspberrypilearning/tweeting-babbage/blob/master/software.md)

**Comment by LornaLynch** [comment]
Just noting that this still needs to be done.

**Comment by lawsie** [comment]
Whole resource now being overhauled and updated by @MarcScott

**Comment by clivebeale** [comment]
I hope you are looking after Biscuits.  He needs polishing once a month.
