### ISSUE TITLE
Missing step in Wiimote setup?

### ISSUE THREAD

**Issue by DougGore** [raspberrypilearning/robo-butler#12]
I was following the Wiimote setup instructions for the Robobutler setup but I hit an issue. A bit of research led me to find I needed to bring up the HCI interface after starting the Bluetooth service with the following command:

sudo hciconfig hci0 up

Without that step I couldn't progress to using the tutorial code. I'm not sure if this is unique to my setup (I'm using a £1 dongle) but it might be useful to list it as a step in case others get caught out in a similar way.

**Comment by lawsie** [comment]
Hi @DougGore - thanks for raising this issue. @MarcScott is in the process of updating this resource, so tagging him here.
