### ISSUE TITLE
Wii Remote Test can lead to breakages

### ISSUE THREAD

**Issue by ryanteck** [raspberrypilearning/robo-butler#6]
The wiimote tester uses GPIO pin 17 the same as the motor board for an unknown reason.

Recommend removing this as if  its on your desk and then you press the button to test...

![img_20141203_163937](https://cloud.githubusercontent.com/assets/1104745/5284353/8625fd1c-7b0b-11e4-8cc5-2a12f926c4a7.jpg)

**Comment by bennuttall** [comment]
@clivebeale is this issue resolved or can it be closed?

**Comment by ryanteck** [comment]
Name's not Clive but I fixed it back then :)

**Comment by bennuttall** [comment]
Talking to @clivebeale as the author :P

**Comment by clivebeale** [comment]
My fix for this issue was not to test robots on your desk.

**Comment by bennuttall** [comment]
Is there a confliction on pin 17 though? Or was that addressed in #7?

Did you want to add a note saying "place your robot on a stand so you can test without it moving away"?

If you're happy to leave it, just close this issue.
