### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/robo-butler#8]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [ ] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
@clivebeale does this resource require any extras that aren't in hardware? Biscuit tin, etc?

**Comment by bennuttall** [comment]
Bump @clivebeale

**Comment by LornaLynch** [comment]
Bump @clivebeale - should I list out biscuit tin etc in an "extras" section?

**Comment by LornaLynch** [comment]
FYI I've added some text in an extras section as a sort of placeholder: it might need adding to?
