### ISSUE TITLE
Alternatives for battery pack?

### ISSUE THREAD

**Issue by mscaldas2012** [raspberrypilearning/robo-butler#9]
Hi,
it seems the battery pack link provided is no longer valid. do you have other suggestions or how to build your own?

thanks,

**Comment by bennuttall** [comment]
@clivebeale was this just a standard USB power pack / emergency phone charger?

http://www.amazon.co.uk/s/ref=nb_sb_ss_i_0_6?url=search-alias%3Dcomputers&field-keywords=emergency%20phone%20charger&sprefix=emerge%2Ccomputers%2C242

**Comment by clivebeale** [comment]
Portable USB charger / battery bank as per you links. Random one I happened to have, nothing special about it.
